import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const pricedown = localFont({
    src: "../fonts/Pricedown.otf",
    variable: "--font-pricedown",
});

const bigbesty = localFont({
    src: "../fonts/Bigbesty.otf",
    variable: "--font-bigbesty",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${pricedown.variable} ${bigbesty.variable} antialiased`}

        >
        {children}
        </body>
        </html>
    );
}