import type { Metadata } from "next";
import { Geist, Geist_Mono, Bebas_Neue, Oswald } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// Den RIGTIGE GTA font
const pricedown = localFont({
    src: "./fonts/pricedown.otf",
    variable: "--font-pricedown",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${pricedown.variable} antialiased`}
        >
        {children}
        </body>
        </html>
    );
}